export const DashboardViolationsTypes = {
    DASHBOARD_VIOLATIONS_REQUEST: 'DASHBOARD_VIOLATIONS_REQUEST',
    DASHBOARD_VIOLATIONS_LOADING: 'DASHBOARD_VIOLATIONS_LOADING',
    DASHBOARD_VIOLATIONS_SUCCESS: 'DASHBOARD_VIOLATIONS_SUCCESS',
    DASHBOARD_VIOLATIONS_FAILURE: 'DASHBOARD_VIOLATIONS_FAILURE',
    DASHBOARD_VIOLATIONS_FLUSH_DATA: 'DASHBOARD_VIOLATIONS_FLUSH_DATA',
};
