export const AwsAccountTypes = {
    ACCOUNT_DETAILS_REQUEST: 'ACCOUNT_DETAILS_REQUEST',
    ACCOUNT_DETAILS_LOADING: 'ACCOUNT_DETAILS_LOADING',
    ACCOUNT_DETAILS_SUCCESS: 'ACCOUNT_DETAILS_SUCCESS',
    ACCOUNT_DETAILS_FAILURE: 'ACCOUNT_DETAILS_FAILURE',
};
