export const ViolationsTypes = {
    VIOLATIONS_REQUEST: 'VIOLATIONS_REQUEST',
    VIOLATIONS_LOADING: 'VIOLATIONS_LOADING',
    VIOLATIONS_SUCCESS: 'VIOLATIONS_SUCCESS',
    VIOLATIONS_FAILURE: 'VIOLATIONS_FAILURE',
    VIOLATIONS_FLUSH_DATA: 'VIOLATIONS_FLUSH_DATA',
    POLICIES_AND_TABLE_VIOLATIONS_REQUEST: 'POLICIES_AND_TABLE_VIOLATIONS_REQUEST',
    POLICIES_AND_TABLE_VIOLATIONS_SUCCESS: 'POLICIES_AND_TABLE_VIOLATIONS_SUCCESS',
};
