export const ViolationsTypes = {
    VIOLATIONS_LOADING: 'VIOLATIONS_LOADING',

    SERVICES_VIOLATIONS_REQUEST: 'SERVICES_VIOLATIONS_REQUEST',
    SERVICES_VIOLATIONS_SUCCESS: 'SERVICES_VIOLATIONS_SUCCESS',
    SERVICES_VIOLATIONS_FAILURE: 'SERVICES_VIOLATIONS_FAILURE',

    POLICIES_VIOLATIONS_REQUEST: 'POLICIES_VIOLATIONS_REQUEST',
    POLICIES_VIOLATIONS_SUCCESS: 'POLICIES_VIOLATIONS_SUCCESS',
    POLICIES_VIOLATIONS_FAILURE: 'POLICIES_VIOLATIONS_FAILURE',

    TABLE_DETAILS_REQUEST: 'TABLE_DETAILS_REQUEST',
    TABLE_DETAILS_SUCCESS: 'TABLE_DETAILS_SUCCESS',
    TABLE_DETAILS_FAILURE: 'TABLE_DETAILS_FAILURE',

    VIOLATIONS_FLUSH_DATA: 'VIOLATIONS_FLUSH_DATA',
};
